#!/bin/bash

# Check if the current directory is a Laravel project
if [ ! -f artisan ]; then
    echo "This doesn't seem to be a Laravel project directory."
    exit 1
fi

# Set file permissions and ownership
echo "Setting permissions and ownership..."
sudo chmod -R 775 storage/
sudo chgrp -R www-data storage bootstrap/cache
sudo chmod -R ug+rwx storage bootstrap/cache
sudo chmod 0777 storage/logs/*

# Run Laravel specific commands
echo "Clearing Laravel caches..."
php artisan view:clear
sudo php artisan cache:clear
php artisan config:clear
php artisan route:clear
php artisan queue:clear
php artisan event:clear
php artisan debugbar:clear
php artisan optimize:clear

# Clear laravel.log file if it exists
echo "Clearing laravel.log file..."
if [ -f storage/logs/laravel.log ]; then
    truncate -s 0 storage/logs/laravel.log
    echo "laravel.log has been cleared."
else
    echo "laravel.log does not exist, no need to clear."
fi

# Give access to all .sqlite files in database/database/
echo "Giving access to sqlite files..."
if ls database/database/*.sqlite 1> /dev/null 2>&1; then
    for sqlite_file in database/database/*.sqlite; do
        sudo chmod 775 "$sqlite_file"
        sudo chgrp www-data "$sqlite_file"
        echo "$sqlite_file has now access."
    done
else
    echo "No .sqlite files found in database/database/, no need to give access."
fi

echo "Project clean complete."
